/*

things to implement

1)implement the modal

1.1 create textfield for todo , date picker to assign submission date , cascader to get priority of task 
and one cascader to implement the task assigning
1.2 the taskId will be generated by system,the assignment date will be noted after the click event is fired,
and the progress field will be in 4 quartes 
1.3 get current user from the globalstate,mainly _id field of the user is important
1.4 check if teamMembers props is empty or not ,if it is empty then the cascader having people will only showing 
self if it not empty then the teamMembers names will be shown in cascader for assigning the task


*/


import React from 'react';
import { usernameState, UserTask , userProjects } from '../../Helper/globeState';
import { Form, Schema, DatePicker, Cascader, Input } from 'rsuite';
import { hookstate, useHookstate } from '@hookstate/core';
import { Task } from '../../Helper/globeState/InitialStae';
import { useRouter } from 'next/router';

const Prioity = [{ value: "high", label: "high" },
{ value: "medium", label: "medium" },
{ value: "low", label: "low" },
]

const InputFile = ({team}) => {
    let teams = []
    const router = useRouter()
    const userDetails = useHookstate(usernameState)
    console.log(userDetails.get())
    const projectState = useHookstate(userProjects)
    console.log(projectState.get())
    const [state, setState] = React.useState(Task)
    React.useEffect(() => {
        if (userDetails.get()._id.length === 0) { router.push("/") }
        else {
          //getUserTeams(userDetails.get()._id).then((res) => setUserteams(res.data))
        }
      }, [1])
    return (
        <>

            <Input name="taskName" onChange={(e) => setState({ ...state, taskName: e })} label="taskName" />
            <DatePicker
                onChange={(e) => { console.log(e); setState({ ...state, SubmissionDate: String(e) }) }}
                format="yyyy-MM-dd HH:mm:ss" />
            <Cascader data={Prioity}
                onSelect={(e) => setState({ ...state, priority: e.value })}
                style={{ width: 224 }} />
            <Cascader data={Prioity}
                onSelect={(e) => setState({ ...state, userName: e.value })}
                style={{ width: 224 }} />    
        </>
    )
};
export default InputFile


