import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";
import { usernameState } from './Helper/globeState'
import { useHookstate } from '@hookstate/core';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
import { app } from './Auth/FirebaseConfig';
import React from 'react';
import DisplayScree from "./DisplayScreen/index"
import axios from 'axios';
import { userDetailsIS } from './Helper/globeState/InitialStae';


const auth = getAuth(app)

export default function Home() {
  const router = useRouter();
  const [user, setUser] = React.useState(userDetailsIS)
  const userDetails = useHookstate(usernameState)

  React.useEffect(() => {
    onAuthStateChanged(auth, async (u) => {
      if (u) {
        userDetails.set(getUserData(u.uid));
        setUser(u)
      }
      else { setUser(null); router.push("/Auth/Login") }
    })
  }, [user])


  return (
    <div className={styles.container}>
      
      <Head>
        <title>Project Managment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DisplayScree  user = {user} />

    </div>
  )
}


export async function getUserData(id) {
  try {
    const res = await (await axios.get(`http://localhost:4000/user/${id}`)).data[0]
    console.log(res)
    return res
  } catch (error) {
    return error
  }
}